### PR TITLE
Implement fixes suggested by HLint

### PR DESCRIPTION
**Pull request by vaibhavsagar**
### Description

Implement style fixes suggested by [HLint](https://github.com/ndmitchell/hlint)

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I've confirmed these changes don't belong in xmonad-contrib instead

  - [ ] I tested my changes with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

  - [ ] I updated the `CHANGES.md` file

### CODE REVIEW

**Comment by geekosaur** [comment]
Following hlint isn't always the wisest idea, as the first travis-ci check demonstrated. hlint, like much of the Haskell community, cares not a whit about backward compatibility.

**Comment by NeQuissimus** [comment]
Maybe it's just me but I find some of the parentheses actually make the code more readable...

**Comment by vaibhavsagar** [comment]
All good now :smile:.

**Comment by vaibhavsagar** [comment]
We could define our own HLint rules if required and override the built-in ones so we are able to ensure a consistent style.

**Comment by geekosaur** [comment]
Well, mostly I don't think much of hlint beyond beginners; heuristics are prone to get confused at higher order code and suggest things that don't typecheck without e.g. `ImpredicativeTypes`.

And as for readability, we blew that with all the `Arrow` stuff. :/

**Comment by vaibhavsagar** [comment]
Fair enough, now I know not to bother with HLint for this project. Let me know if you'd like a smaller/more focused pull request (e.g. one with the parentheses untouched), otherwise feel free to close :smile:

**Comment by pjones** [comment]
Changes like these are easier to accept when they are due to someone refactoring code or adding a feature.  Accepting a patch that touches several files just to make stylistic changes doesn't make sense to me.

We appreciate the effort @vaibhavsagar but perhaps you could do this in smaller increments as you work on one of the other issues?

Thanks.

**Pull request closed without merging**
