### PR TITLE
Add help command to help message.

### LINKED ISSUE #287: Update the xmonad cheatsheet
The [current cheatsheet](https://wiki.haskell.org/wikiupload/b/b8/Xmbindings.png) is really nice and still quite up-to-date; with the exception of `M-S-/` missing to bring up and `xmessage` window with the default keybindings.  It would be great to redo it for the next release! 

Indeed, even the [help function](https://github.com/xmonad/xmonad/blob/master/src/XMonad/Config.hs#L289) doesn't mention its own keybinding!  This could be fixed in tandem with the new picture. 

### Checklist

  - [X] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  ~~- [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)~~

### PR DESCRIPTION
**Pull request by mzrinsky**
Attempt to contribute to xmonad,
and add a simple line to the help message,
containing the help command itself.

Fixes: #287

### Description

Just wanted to help out, and saw this "low hanging fruit", also the Xmbindings.png image is actually what helped me originally learn to use XMonad so really I wanted to help update that.  The code changes here go along with that.

I used the svg file at  as a base, and fixed a few minor differences I saw between that and the existing png file.
Namely the XMonad logo was missing from the svg, and a few buttons were misaligned by a few pixels (not really a huge deal).
I also updated the XMonad version at the top to  0.13 while I was at it, and added a missing white background behind the second line of text (that begins "By default the xmonad").
The end result is not a 1:1 copy of the original png, but seemed close enough to me.

GitHub does not allow uploading svg files (apparently), so I plan on uploading both to the wiki, I have obtained a wiki account to do so.  I will hold off on that until I get approval here on the changes, unless told otherwise.

I was unsure if I should go with "Show help message", or "Show key binds", (I ended up with the latter obviously) space is limited, so suggestions are welcome.

Xmbindings

If there is anything I broke, or needs more work, don't hesitate to let me know.

Thanks!

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I've confirmed these changes don't belong in xmonad-contrib instead

  - [ ] I tested my changes with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

  - [x] I updated the `CHANGES.md` file

### CODE REVIEW

**Review by slotThe — COMMENTED** [review]
Thank you for the contribution :tada:  I think the cheat sheet looks great!

> Fix #287

This should read `Fixes` so GitHub can pick up on it (but that's not so essential :))

> I used the svg file at  as a base, and fixed a few minor differences I saw between that and the existing png file.
> Namely the XMonad logo was missing from the svg, and a few buttons were misaligned by a few pixels (not really a huge deal).
> I also updated the XMonad version at the top to 0.13 while I was at it, and added a missing white background behind the second line of text (that begins "By default the xmonad").
> The end result is not a 1:1 copy of the original png, but seemed close enough to me.
> 
> GitHub does not allow uploading svg files (apparently), so I plan on uploading both to the wiki, I have obtained a wiki account to do so. I will hold off on that until I get approval here on the changes, unless told otherwise.

Actually, we prefer to have all things xmonad on the [website](https://xmonad.org/) nowadays (there is a chance we'll be kicked out of the Haskell wiki at some point in the future).  The website is build from a [repo](https://github.com/xmonad/xmonad-web) and an up-to-date svg is available [here](https://github.com/xmonad/xmonad-web/blob/gh-pages/images/cheat/xmbindings.svg).  Not much has changed from the version you used (just that we're on Libera for IRC now), so it'd be completely fine to just fix these small differences and use your version. 

Also, why the update to 0.13 only?  0.15 was released quite a while ago and we're on our way to 0.17.  I think having it as up-to-date as possible would be nice here.

> I was unsure if I should go with "Show help message", or "Show key binds", (I ended up with the latter obviously) space is limited, so suggestions are welcome.

Perhaps `Show keybindings`?  Although maybe that's not explicit enough that these are the _default_ keybindings and I think `Show default keybindings` is too long.

**Comment by mzrinsky** [comment]
> 
> This should read `Fixes` so GitHub can pick up on it (but that's not so essential :))
> 
I can just amend my commit message, I would rather fix it.
 
> Actually, we prefer to have all things xmonad on the [website](https://xmonad.org/) nowadays (there is a chance we'll be kicked out of the Haskell wiki at some point in the future). The website is build from a [repo](https://github.com/xmonad/xmonad-web) and an up-to-date svg is available [here](https://github.com/xmonad/xmonad-web/blob/gh-pages/images/cheat/xmbindings.svg). Not much has changed from the version you used (just that we're on Libera for IRC now), so it'd be completely fine to just fix these small differences and use your version.
> 
> Also, why the update to 0.13 only? 0.15 was released quite a while ago and we're on our way to 0.17. I think having it as up-to-date as possible would be nice here.

Thanks for pointing that out, I think i will actually start fresh from the svg in the [repo](https://github.com/xmonad/xmonad-web), as that makes way more sense and then I can just make a PR there.

As for using 0.13, for whatever reason I just looked at the branch drop down on GitHub, I should have known better I am running 0.15 myself.  I will fix that too.

Additionally I think `Show default keybindings` will fit just fine, and reads a lot better, so I will go with that.

Thanks for the guidance!

**Comment by mzrinsky** [comment]
Updated the branch with a fixed author and commit message.
Let me know if you would like to see any other changes.

Thanks!

**Comment by slotThe** [comment]
Looks good to me, cheers!

**Pull request merged**
