### PR TITLE
man/Makefile: Add a clean target

### PR DESCRIPTION
**Pull request by felixonmars**
### Description

Add a clean target to ease cleanup of generated files.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I've confirmed these changes don't belong in xmonad-contrib instead

  - [x] I've considered how to best test these changes (property, unit,
        manually, ...) and concluded: XXX

  - [ ] I updated the `CHANGES.md` file

### CODE REVIEW

**Comment by liskin** [comment]
The Makefile isn't intended to be used by end-users or even distributors (but it should say that!, and I'll update this later), it's our internal tooling to *update* the generated files, which are committed to git and shipped in the tarball.

So I wonder, what's the use case for deleting these files?

**Comment by felixonmars** [comment]
> what's the use case for deleting these files?

As a distribution packager, we usually prefer to avoid using any pre-generated files as possible, because the ability to re-construct artifacts from the real source format is important to us.

It's totally fine if this Makefile is not meant to be stable and subjected to change at any time, we can adapt to it or probably just remove the generated files manually like what is done now.

**Comment by liskin** [comment]
I see. What about `make --always-make` then? That also regenerates all the files and doesn't require a `clean` target listing all the generated files; and it's (almost) exactly what we run in our CI.

**Comment by felixonmars** [comment]
That works too! Thanks :)

**Pull request closed without merging**
