### PR TITLE
Add support for (re-) building using script

### PR DESCRIPTION
**Pull request by Philonous**
Based on [geekosaur's comment](https://github.com/xmonad/xmonad/pull/46#issuecomment-254020572). 
Supersedes #46, related to #50 

[Example build script](https://gist.github.com/Philonous/b29f8068ff8d840b21e651056c5d8e91)

### CODE REVIEW

**Comment by codygman** [comment]
I was still a bit lost even after reading all above and linked conversation, looking at [Philonous' xmonad-config repository](https://github.com/Philonous/xmonad-config) cleared things up for me;

**Comment by colonelpanic8** [comment]
@Philonous Fix merge conflicts?

**Comment by pjones** [comment]
In order to merge this PR, please do the following:

  1. Fix the current merge conflict.

  2. Update the `CHANGES.md` file.

**Comment by Philonous** [comment]
Re-based onto HEAD and updated CHANGES.md

**Comment by pjones** [comment]
Thanks!

**Pull request merged**
