### PR TITLE
Cleanup build warnings

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

### Description

Include a description for your changes, including the motivation
behind them.

### Checklist

  - [ ] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I've confirmed these changes don't belong in xmonad-contrib instead

  - [ ] I tested my changes with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

  - [ ] I updated the `CHANGES.md` file

### CODE REVIEW

**Comment by pjones** [comment]
@gliptak Would you please give a little detail about which compilers you are fixing warnings for and which warnings.  One of the reasons these haven't been addressed yet is because different versions of GHC produce different warnings.

Thanks.

**Comment by gliptak** [comment]
Using the ```stack.yaml``` included:
```
➜ stack exec -- ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.1
```
```
/tmp/xmonad/src/XMonad/Core.hs:39:1: warning: [-Wunused-imports]
    The import of ‘Control.Applicative’ is redundant
      except perhaps to import instances from ‘Control.Applicative’
    To import instances alone, use: import Control.Applicative()
/tmp/xmonad/src/XMonad/Operations.hs:31:1: warning: [-Wunused-imports]
    The import of ‘Control.Applicative’ is redundant
      except perhaps to import instances from ‘Control.Applicative’
    To import instances alone, use: import Control.Applicative()
/tmp/xmonad/src/XMonad/Main.hs:200:9: warning: [-Wunused-local-binds]
    Defined but not used: ‘lreads’
```
I haven't checked if changes introduce additional warnings with lower ```ghc``` versions.

**Comment by geekosaur** [comment]
"Fixing" that doesn't introduce warnings in older versions. It introduces *errors*, specifically in versions older than 7.10.

**Comment by gliptak** [comment]
@geekosaur Please review https://travis-ci.org/gliptak/xmonad/builds/222446488

**Comment by geekosaur** [comment]
I haven't forgotten or rejected this, just a bit overloaded. :/

**Comment by mgsloan** [comment]
Hmm, is it actually valuable to support versions of ghc older than 7.10?

**Comment by geekosaur** [comment]
Do we still need to care about ancient Debian that shipped 7.6.3 and skipped 7.8 entirely? That was the main thing keeping 7.6 support around for so long.

**Pull request merged**
