### PR TITLE
Make ScreenDetail a newtype and RationalRect strict in its contents

### PR DESCRIPTION
**Pull request by ghost**
This seems to be the original intention. Should not have much of an effect but
could help with edge-case space leaks.

### Description

The change to ScreenDetail should not have much of an effect, but if there is one it should be an improvement.

The change to RationalRect will force all changes in dimensions to be calculated when they are 'made', rather than when they are used. As long as the calculations are simple, this should be a net improvement even if not all of the values are used.

Overall this is more of a 'cleanup' than an improvement.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I've confirmed these changes don't belong in xmonad-contrib instead

  - [x] I tested my changes with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

  - [x] I updated the `CHANGES.md` file

### CODE REVIEW

**Comment by slotThe** [comment]
This looks nice to me, @wygulmage do you mind rebasing on top of current `master`?

**Comment by ghost** [comment]
> This looks nice to me, @wygulmage do you mind rebasing on top of current `master`?

Should be good now.

**Comment by slotThe** [comment]
@psibi I think this looks good, what do you say?

**Review by psibi — APPROVED** [review]
Looks okay to me. I will merge this in a couple of days unless anybody has any objection.

**Comment by ghost** [comment]
Just for the record, I've been using this change for over a year with no problems.

**Comment by psibi** [comment]
Thank you!

**Pull request merged**
